### ISSUE TITLE
Slide crashing upon opening

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide-iOS#215] opened 2018-06-13 15:14 UTC
iPhone SE 10.2.1
Slide 1.0.1 (15)

https://streamable.com/digpe

**Comment by ccrama** [comment] 2018-06-13 16:18
I'm on an iOS 10 emulator and can't reproduce this, have you tried reinstalling?

**Comment by ccrama** [comment] 2018-06-14 01:34
Should be fixed in build 16

**Closed** 2018-06-15 00:50 UTC
