### ISSUE TITLE
Sharing is not functional

### ISSUE THREAD

**Issue by cool00geek** [ccrama/Slide-iOS#203] opened 2018-05-25 22:24 UTC
Device: iPhone 6s  
OS Version: iOS 11.3.1  
Slide Version: 0.5.12  

Sharing a comment: Everything works well until the actual sharing part. Tapping on an app to share gives various errors depending on the app. Facebook Messenger says "Can't send message, Check your connection and try again.", Google Hangouts shows a popup "Problem with sharing, try again later", and other apps, such as notes and Google Keep create a blank note, making me believe the apps are not receiving any data to share - the share URL is not being passed. If I use the "copy" function and try to paste it elsewhere, no data is pasted.  

Sharing a post (post link or link to comments in a link post): I have not been able to find the button. In Android, on the bottom left of a post, there is a menu button that allows sharing the post link or the comments link, but I have not been able to find this.

Sharing an image: On Android, when an image is opened, there is the menu button on the bottom right, and pressing it there is a share url or Share Image button. Previously, this menu could not be accessed but should be fixed in #201. However, the fixes have not made it to test flight and I have not been able to verify that sharing an image is fixed.

Once again, thank you for this wonderful app!

**Comment by ccrama** [comment] 2018-05-26 19:37
Hmm I am not able to reproduce on my iPhone 6s, there is a share comments and share content button on posts as well, and I'm able to share images/gifs to any app on the list. Sharing comments was sharing a null link (which I just fixed), but would it be possible for you to re-install the app as it is possible some code didn't update on your installation?

**Comment by cool00geek** [comment] 2018-05-28 23:54
Sorry for the late response...  
Upon reinstalling, this is what I've found:  

"Share comment permalink" (Directly from post): Works fine  
"Share content" (Directly from post): Unpredictable. Sometimes it crashes, sometimes it works fine.
"Share comments": Crash

The other issues should be fixed by now (just not pushed to testflight), but the share content is the only sharing option that seems to be completely not functioning.

**Comment by ccrama** [comment] 2018-05-28 23:57
All should be fixed now then :)

**Closed by ccrama** 2018-05-28 23:57 UTC
