### ISSUE TITLE
View History

### ISSUE THREAD

**Issue by a60wattfish** [ccrama/Slide-iOS#1056] opened 2020-08-12 10:48 UTC
Could you add a page for viewing the history of which posts you have looked at? I believe this information is already stored in the app.

**Comment by colejd** [comment] 2020-08-12 16:18
This will be a feature in 6.0. It's already in if you check out the beta, though it is a bit buried. In the new home menu, go to "more shortcuts" and tap "post history".

**Comment by colejd** [comment] 2020-08-12 16:21
Closing as a dupe of #1050. Feel free to leave a comment on that one if you have anything.

**Closed by colejd** 2020-08-12 16:21 UTC
