### ISSUE TITLE
More consistent up vote/down vote pattern

### ISSUE THREAD

**Issue by laserstrike** [ccrama/Slide-iOS#141] opened 2017-08-06 00:58 UTC
On a post the alignment is upvote downvote. With a comment it's downvote upvote. 

Could they both be the same for consistency? I think upvote downvote looks better in general, but I'm no expert. Is it the same with slide on Android?

**Comment by WickedColdfront** [comment] 2017-08-06 04:57
I noticed the same thing - I think this is a Duplicate of #117 

I agree that upvote/downvote is the right order, as this would match the native Reddit app.

**Comment by laserstrike** [comment] 2017-08-06 05:00
Crap. You're right. Please close.

**Closed** 2017-08-06 05:02 UTC
