### ISSUE TITLE
Clicking “Load More” in a comments thread causes the app to become unresponsive 

### ISSUE THREAD

**Issue by russjr08** [ccrama/Slide-iOS#371] opened 2018-08-12 03:40 UTC
Hello!

I’m currently on an iPhone 7 Plus running iOS 12 Beta 6, and using Slide 1.5 Build 33. 

For some reason, any time I try to click “Load More” in a comments thread, Slide eventually just turns to black, and is no longer responsive. I then need to go into the task switcher, and force close Slide. 

[Here’s an example of what I’m seeing](https://drive.google.com/open?id=18lrrGGcNh5okzzXCxs89y5niiLa1M_SR)

**Comment by ccrama** [comment] 2018-08-12 04:33
Does this happen on every thread?

**Comment by russjr08** [comment] 2018-08-12 09:41
Unfortunately, yep.

**Comment by ccrama** [comment] 2018-08-12 16:37
Should be fixed for the next update, please re-open this if not!

**Comment by russjr08** [comment] 2018-08-12 20:53
Hmm, I’ve updated to build 34, and am seeing the exact same issue sadly.

**Comment by ccrama** [comment] 2018-08-12 20:54
I am not able to reproduce this (on iOS 12 iPhone 6s, iPad pro). Are you logged into an account in Slide?

**Comment by russjr08** [comment] 2018-08-12 20:58
So it turns out this build did fix the issue, I just deleted the app and reinstalled, and the problem disappeared. 

Sorry for the false alarm! (Next time I’ll remember the good ole “Have you tried turning it off and back on again?”) 😁

**Comment by ccrama** [comment] 2018-08-13 17:51
Fixed! It was actually the long press swap option :D so you weren't wrong that a reinstall fixed, but the option was actually the issue

**Closed by ccrama** 2018-08-13 17:51 UTC
Labels: needs reproduction
