### ISSUE TITLE
Top of the app is cut off 

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide-iOS#198] opened 2018-05-23 16:58 UTC
Slide v0.5.11, iPhone SE 10.2.1

Video of the issue:
https://streamable.com/gc86v

**Comment by ccrama** [comment] 2018-05-23 17:04
Interesting, what device are you using? Cannot reproduce on iPad or iPhone 6s

**Comment by ccrama** [comment] 2018-05-23 17:04
What happens if you enable the bottom bar in comments?

**Comment by incIined** [comment] 2018-05-23 17:10
@ccrama no change.

**Comment by ccrama** [comment] 2018-05-23 17:27
Also how are you doing video on iOS 10?

**Comment by incIined** [comment] 2018-05-23 17:39
@ccrama yep, cut off on main page. 

I'm using the Cydia tweak "EasyRecord" by SparkDev.

**Comment by ccrama** [comment] 2018-05-23 17:44
Ah gotcha, should be fixed now

**Comment by ccrama** [comment] 2018-05-23 17:45
If it is not fixed in the update I'm pushing out momentarily, please re-open this!

**Comment by incIined** [comment] 2018-05-24 23:28
Unfortunately, it is not fixed in 0.5.12.

https://streamable.com/egdk4

**Comment by ccrama** [comment] 2018-05-26 21:13
I'm probably going to have to buy an iOS 10 device to test this on

**Comment by ccrama** [comment] 2018-06-11 22:10
Fixed

**Closed by ccrama** 2018-06-11 22:10 UTC
