### ISSUE TITLE
Make volume slider less obtrusive on video player

### ISSUE THREAD

**Issue by WickedColdfront** [ccrama/Slide-iOS#454] opened 2018-08-30 03:12 UTC
I’m not sure if this is possible, but it would be nice if the volume slider on videos looked more like how the slider looks in the YouTube app.

**Comment by colejd** [comment] 2018-09-06 03:51
We're working on the video player for the next update! This is definitely something we're looking at. Closing since this is technically a duplicate of #322; feel free to bring further discussion on this topic there.

**Closed by colejd** 2018-09-06 03:51 UTC
